version: '3.5'

services:
  specification-subject-postgres:
    container_name: specification-subject-postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    command: >
      postgres -c log_statement=all -c log_duration=on
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"


  specification-subject-api:
    container_name: specification-subject-api
    image: specification-subject:latest
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ../.env
    working_dir: /usr/src/project/src/
    depends_on:
      - specification-subject-postgres